name: 🚀 pusher

on:
  push:
    branches:
      - main

jobs:
  dispatch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Disparar Workflow no Repositório de Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ArthurBitt/repo_listener_teste
          event-type: test
          client-payload: { "branch": "${{ github.ref_name }}", "repo": "ArthurBitt/repo_caller_teste" }
